-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 16:29:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas_sucos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema sucos_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sucos_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sucos_vendas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vendas_sucos` ;

-- -----------------------------------------------------
-- Table `vendas_sucos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`clientes` (
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `ENDERECO` VARCHAR(150) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(50) NULL DEFAULT NULL,
  `CEP` VARCHAR(8) NULL DEFAULT NULL,
  `DATA_NASCIMENTO` DATE NULL DEFAULT NULL,
  `IDADE` INT NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMITE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUME_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMEIRA_COMPRA` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `COMISSAO` FLOAT NULL DEFAULT NULL,
  `DATA_ADMISSAO` DATE NULL DEFAULT NULL,
  `FERIAS` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`notas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `DATA_VENDA` DATE NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPOSTO` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `FK_CLIENTES` (`CPF` ASC) VISIBLE,
  INDEX `FK_VENDEDORES` (`MATRICULA` ASC) VISIBLE,
  CONSTRAINT `FK_CLIENTES`
    FOREIGN KEY (`CPF`)
    REFERENCES `vendas_sucos`.`clientes` (`CPF`),
  CONSTRAINT `FK_VENDEDORES`
    FOREIGN KEY (`MATRICULA`)
    REFERENCES `vendas_sucos`.`vendedores` (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`produtos` (
  `CODIGO` VARCHAR(10) NOT NULL,
  `DESCRITOR` VARCHAR(100) NULL DEFAULT NULL,
  `SABOR` VARCHAR(100) NULL DEFAULT NULL,
  `TAMANHO` VARCHAR(50) NULL DEFAULT NULL,
  `EMBALAGEM` VARCHAR(50) NULL DEFAULT NULL,
  `PRECO_LISTA` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`itens_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`itens_notas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `CODIGO` VARCHAR(10) NOT NULL,
  `QUANTIDADE` INT NULL DEFAULT NULL,
  `PRECO` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO`),
  INDEX `FK_PRODUTOS` (`CODIGO` ASC) VISIBLE,
  CONSTRAINT `FK_NOTAS`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `vendas_sucos`.`notas` (`NUMERO`),
  CONSTRAINT `FK_PRODUTOS`
    FOREIGN KEY (`CODIGO`)
    REFERENCES `vendas_sucos`.`produtos` (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`cliente` (
  `nome` VARCHAR(40) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concessionaria`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`veiculo` (
  `codVeiculo` INT NOT NULL AUTO_INCREMENT,
  `corVeiculo` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `ano` YEAR NOT NULL,
  PRIMARY KEY (`codVeiculo`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concessionaria`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`vendedor` (
  `codVendedor` INT NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `de_ferias` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codVendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concessionaria`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`nota_fiscal` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `CPF_Cliente` VARCHAR(15) NOT NULL,
  `codVeiculo` INT NOT NULL,
  `codVendedor` INT NOT NULL,
  `preco` DECIMAL(8,2) NULL DEFAULT NULL,
  `data_venda` TIMESTAMP NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `CPF_Cliente` (`CPF_Cliente` ASC) VISIBLE,
  INDEX `codVeiculo` (`codVeiculo` ASC) VISIBLE,
  INDEX `codVendedor` (`codVendedor` ASC) VISIBLE,
  CONSTRAINT `nota_fiscal_ibfk_1`
    FOREIGN KEY (`CPF_Cliente`)
    REFERENCES `concessionaria`.`cliente` (`CPF`),
  CONSTRAINT `nota_fiscal_ibfk_2`
    FOREIGN KEY (`codVeiculo`)
    REFERENCES `concessionaria`.`veiculo` (`codVeiculo`),
  CONSTRAINT `nota_fiscal_ibfk_3`
    FOREIGN KEY (`codVendedor`)
    REFERENCES `concessionaria`.`vendedor` (`codVendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `concessionaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`usuario` (
  `username` INT NULL DEFAULT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `administrador` TINYINT(1) NOT NULL,
  INDEX `username` (`username` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`username`)
    REFERENCES `concessionaria`.`vendedor` (`codVendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `sucos_vendas` ;

-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_produtos` (
  `CODIGO_DO_PRODUTO` VARCHAR(10) NOT NULL,
  `NOME_DO_PRODUTO` VARCHAR(50) NULL DEFAULT NULL,
  `EMBALAGEM` VARCHAR(20) NULL DEFAULT NULL,
  `TAMANHO` VARCHAR(10) NULL DEFAULT NULL,
  `SABOR` VARCHAR(20) NULL DEFAULT NULL,
  `PRECO_DE_LISTA` FLOAT NOT NULL,
  PRIMARY KEY (`CODIGO_DO_PRODUTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `PERCENTUAL_COMISSAO` FLOAT NULL DEFAULT NULL,
  `DATA_ADMISSAO` DATE NULL DEFAULT NULL,
  `DE_FERIAS` BIT(1) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_clientes` (
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `ENDERECO_1` VARCHAR(150) NULL DEFAULT NULL,
  `ENDERECO_2` VARCHAR(150) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(2) NULL DEFAULT NULL,
  `CEP` VARCHAR(8) NULL DEFAULT NULL,
  `DATA_DE_NASCIMENTO` DATE NULL DEFAULT NULL,
  `IDADE` SMALLINT NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMITE_DE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUME_DE_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMEIRA_COMPRA` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`notas_fiscais` (
  `CPF` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `DATA_VENDA` DATE NULL DEFAULT NULL,
  `NUMERO` INT NOT NULL,
  `IMPOSTO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `MATRICULA` (`MATRICULA` ASC) VISIBLE,
  INDEX `CPF` (`CPF` ASC) VISIBLE,
  CONSTRAINT `notas_fiscais_ibfk_1`
    FOREIGN KEY (`MATRICULA`)
    REFERENCES `sucos_vendas`.`tabela_de_vendedores` (`MATRICULA`),
  CONSTRAINT `notas_fiscais_ibfk_2`
    FOREIGN KEY (`CPF`)
    REFERENCES `sucos_vendas`.`tabela_de_clientes` (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`itens_notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`itens_notas_fiscais` (
  `NUMERO` INT NOT NULL,
  `CODIGO_DO_PRODUTO` VARCHAR(10) NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `PRECO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO_DO_PRODUTO`),
  INDEX `CODIGO_DO_PRODUTO` (`CODIGO_DO_PRODUTO` ASC) VISIBLE,
  CONSTRAINT `itens_notas_fiscais_ibfk_1`
    FOREIGN KEY (`CODIGO_DO_PRODUTO`)
    REFERENCES `sucos_vendas`.`tabela_de_produtos` (`CODIGO_DO_PRODUTO`),
  CONSTRAINT `itens_notas_fiscais_ibfk_2`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `sucos_vendas`.`notas_fiscais` (`NUMERO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `sucos_vendas` ;

-- -----------------------------------------------------
-- Placeholder table for view `sucos_vendas`.`vw_maiores_embalagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`vw_maiores_embalagens` (`EMBALAGEM` INT, `MAIOR_PRECO` INT);

-- -----------------------------------------------------
-- View `sucos_vendas`.`vw_maiores_embalagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sucos_vendas`.`vw_maiores_embalagens`;
USE `sucos_vendas`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `sucos_vendas`.`vw_maiores_embalagens` AS select `sucos_vendas`.`tabela_de_produtos`.`EMBALAGEM` AS `EMBALAGEM`,max(`sucos_vendas`.`tabela_de_produtos`.`PRECO_DE_LISTA`) AS `MAIOR_PRECO` from `sucos_vendas`.`tabela_de_produtos` group by `sucos_vendas`.`tabela_de_produtos`.`EMBALAGEM`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
